# Generated by Django 4.0.4 on 2022-05-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='write',
            new_name='writer',
        ),
    ]
