# Generated by Django 4.0.4 on 2022-05-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_write_board_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='write',
            new_name='writer',
        ),
    ]
