CREATE TABLE BANK (
BANK_CODE INT PRIMARY KEY,
BANK_NAME VARCHAR(20)
);
CREATE TABLE ACCOUNT (
BANK_CODE INT, 
ACCOUNT_NUMBER INT PRIMARY KEY,
ACCOUNT_HOLDER VARCHAR(20),
BALANCE INT
);

INSERT INTO BANK VALUES ('1', '국민은행');
INSERT INTO BANK VALUES ('2', '신한은행');
INSERT INTO ACCOUNT VALUES ('1', '1234567', '김철수', 100000);
INSERT INTO ACCOUNT VALUES ('2', '9101112', '박철수',200000);

SELECT B.BANK_CODE, BANK_NAME, ACCOUNT_NUMBER, ACCOUNT_HOLDER, BALANCE
FROM BANK B, ACCOUNT A
WHERE B.BANK_CODE=A.BANK_CODE;