CREATE TABLE BOOK (
BOOK_CODE INT PRIMARY KEY,
BOOK_NAME VARCHAR(20),
PRESS VARCHAR(20),
PRICE INT, 
AMOUNT INT
);

INSERT INTO BOOK VALUES (1, 'JAVA', '공룡', 20000, 10);
INSERT INTO BOOK VALUES (2, 'DB', '글마루', 20000, 15);
INSERT INTO BOOK VALUES (3, 'DATA', '영진', 20000, 20);
INSERT INTO BOOK VALUES (4, 'PYTHON', '새싹', 20000, 25);

SELECT*FROM BOOK;
SELECT BOOK_CODE, BOOK_NAME, PRESS, PRICE, AMOUNT, PRICE*AMOUNT 금액
FROM BOOK;